### ISSUE TITLE
Energized website is down.

### ISSUE THREAD

**Issue by anudeepreddy** [EnergizedProtection/block#768] opened 2021-07-17 11:14 UTC
- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [ ] Other Issue

Your website seems to be down. I am unable to fetch things in the magisk module and also I can't access your site in the browser.

**Comment by lssong99** [comment] 2021-07-17 12:21
Yes, I concur... It was down for almost 24 hours....

**Comment by asterriya** [comment] 2021-07-17 14:50
Same for me

**Comment by SaberAkiyama** [comment] 2021-07-18 03:10
Same. I was update the filter since 2-3 days ago

**Comment by ahmed-tasaly** [comment] 2021-07-18 11:19
same

**Comment by Kraze7790** [comment] 2021-07-18 11:35
Same here

**Comment by lssong99** [comment] 2021-07-18 14:20
Can anyone post a latest hosts somewhere?

**Comment by Kraze7790** [comment] 2021-07-18 14:30
Use adgaurd

**Comment by gallegonovato** [comment] 2021-07-18 19:44
Good afternoon: they still do not go. And before they had a gitlab but it doesn't allow to enter either. Do you know if they will go again? A hug

**Comment by Poincare1** [comment] 2021-07-18 23:28
I am also experiencing errors with the web site. The site appears to be completely down.

**Comment by ndr48291** [comment] 2021-07-19 20:12
who will check this issue?

**Comment by ndr48291** [comment] 2021-07-19 20:13
@AdroitAdorKhan

**Comment by MaximMaximS** [comment] 2021-07-20 20:53
This from in Telegram group, I think there is no new information about it yet. 

>#ANNOUNCEMENT
Our web server (energized.pro) is facing some issues, and hence users will (temporarily) not be able to install/update Energized packs..
Inconvenience is highly regretted, we're working on solving this.

**Comment by TheSSJ** [comment] 2021-07-23 13:48
> This from in Telegram group, I think there is no new information about it yet.
> 
> > #ANNOUNCEMENT
> > Our web server (energized.pro) is facing some issues, and hence users will (temporarily) not be able to install/update Energized packs..
> > Inconvenience is highly regretted, we're working on solving this.

It's just odd that all blocklists disappeared from github as well. If their web page has problems it's fine, but it doesn't explain the GitHub content being affected by this as well

**Comment by unofficial-hima** [comment] 2021-07-23 18:54
> > This from in Telegram group, I think there is no new information about it yet.
> > > #ANNOUNCEMENT
> > > Our web server (energized.pro) is facing some issues, and hence users will (temporarily) not be able to install/update Energized packs..
> > > Inconvenience is highly regretted, we're working on solving this.
> 
> It's just odd that all blocklists disappeared from github as well. If their web page has problems it's fine, but it doesn't explain the GitHub content being affected by this as well

I wondered the same thing, maybe there is more to it
hopefully it will be explained

**Comment by badmojr** [comment] 2021-07-23 19:01
Head dev & maintainer, @AdroitAdorKhan  has been inactive & AWOL for a while now.
All my attempts to get in touch with him have been fruitless.

Maybe @AvinashReddy3108 can chip in as to what's going on.

**Comment by chandr1000** [comment] 2021-07-25 08:02
I think it was caused by BGP issues?

```
root@OpenWrt:~# nslookup block.energized.pro
Server:         ::1
Address:        ::1#53

Name:      block.energized.pro
Address 1: 136.243.241.83
*** Can't find block.energized.pro: No answer
root@OpenWrt:~# ping -c 5 136.243.241.83
PING 136.243.241.83 (136.243.241.83): 56 data bytes

--- 136.243.241.83 ping statistics ---
5 packets transmitted, 0 packets received, 100% packet loss
```

I can't even ping IP range 136.243.241.0 - 136.243.241.255

Totally down

**Comment by cassiomolin** [comment] 2021-07-27 11:41
No updates so far? @AdroitAdorKhan seems to be inactive these days.
Has anyone managed to get in touch with him?

**Comment by Kraze7790** [comment] 2021-07-27 11:47
Im using ADGAURD with root access
It works good but
Not like
ENERGIZED PROTECTION

**Comment by anudeepreddy** [comment] 2021-08-05 03:09
Closing this issue as the issue is being addressed

**Comment by akorn** [comment] 2021-08-06 13:26
Why close it now? Shouldn't you leave it open until it's fixed?

**Comment by SaberAkiyama** [comment] 2021-08-09 01:36
So, still issue yet?

**Comment by akorn** [comment] 2021-08-09 07:31
> So, still issue yet?

http://energized.pro/ and http://block.energized.pro/ are both reachable as of now but appear to host no content.

**Comment by SaberAkiyama** [comment] 2021-08-09 07:40
> > So, still issue yet?
> 
> http://energized.pro/ and http://block.energized.pro/ are both reachable as of now but appear to host no content.

Yeah, but it's error code 403 Forbidden by nginx

**Comment by AdroitAdorKhan** [comment] 2021-08-09 07:41
We are almost done. Give us few more time.

**Comment by SaberAkiyama** [comment] 2021-08-09 08:09
> We are almost done. Give us few more time.

You're back! My goodness, you're alive! I've thought you'd infected or something?

**Comment by joehillen** [comment] 2021-08-19 21:48
Looks like the site and links are working again, but the status says "Inactive" even though it says the packs were updated today. What does "Inactive" mean here?

**Comment by AdroitAdorKhan** [comment] 2021-08-20 15:27
> Looks like the site and links are working again, but the status says "Inactive" even though it says the packs were updated today. What does "Inactive" mean here?

Well, it's to check whether you are using Energized Pro in your system or not!

**Comment by joehillen** [comment] 2021-08-20 15:38
Aha! Thank you. Anyway. This ticket should be closed.

**Comment by ToufikDevDz** [comment] 2021-08-22 09:16
> > Looks like the site and links are working again, but the status says "Inactive" even though it says the packs were updated today. What does "Inactive" mean here?
> 
> Well, it's to check whether you are using Energized Pro in your system or not!

Thank you brother!
Please tell me why porn lite pack has less than 40 000 domains now, not like its older versions?
And i apologize for putting my question here i didn't find your email! Thank you!

**Closed** 2021-08-30 04:35 UTC

**Comment by gyCfjSnO** [comment] 2021-09-18 14:12
Can anyone explain what happened and why the blocklists all disappeared from GitHub

**Comment by AdroitAdorKhan** [comment] 2021-09-18 14:15
> Can anyone explain what happened and why the blocklists all disappeared from GitHub

check at website instead energized.pro

**Comment by gyCfjSnO** [comment] 2021-09-18 14:39
> > Can anyone explain what happened and why the blocklists all disappeared from GitHub
> 
> check at website instead [energized.pro ](https://energized.pro)

Doesn't mention why the website went offline a month ago and also doesn't explain why the lists disappeared from GitHub. Did you read my question in full?

**Comment by SaberAkiyama** [comment] 2021-09-18 14:43
> > > Can anyone explain what happened and why the blocklists all disappeared from GitHub
> > 
> > 
> > check at website instead [energized.pro ](https://energized.pro)
> 
> Doesn't mention why the website went offline a month ago and also doesn't explain why the lists disappeared from GitHub. Did you read my question in full?

Mine was active on Energized website. Maybe is your adblock extension was an issue

**Comment by AdroitAdorKhan** [comment] 2021-09-18 14:48
> > > Can anyone explain what happened and why the blocklists all disappeared from GitHub
> > 
> > 
> > check at website instead [energized.pro ](https://energized.pro)
> 
> Doesn't mention why the website went offline a month ago and also doesn't explain why the lists disappeared from GitHub. Did you read my question in full?

if you knew the website is up and files are available on the website and not here in github, you could have already guessed that their was some issue storing the lists here in github! 

and, the website went offline because we had an issue with the previous server.

**Comment by gyCfjSnO** [comment] 2021-09-18 14:52
> > > > Can anyone explain what happened and why the blocklists all disappeared from GitHub
> > > 
> > > 
> > > check at website instead [energized.pro ](https://energized.pro)
> > 
> > 
> > Doesn't mention why the website went offline a month ago and also doesn't explain why the lists disappeared from GitHub. Did you read my question in full?
> 
> if you knew the website is up and files are available on the website and not here in github, you could have already guessed that their was some issue storing the lists here in github!
> 
> and, the website went offline because we had an issue with the previous server.

Seems odd that the website went offline and the GitHub lists also were removed at the same time and no solid explanation as to why. I'm trying to find an answer but I'm having to dig around for it.

**Comment by AdroitAdorKhan** [comment] 2021-09-18 14:57
> > > > > Can anyone explain what happened and why the blocklists all disappeared from GitHub
> > > > 
> > > > 
> > > > check at website instead [energized.pro ](https://energized.pro)
> > > 
> > > 
> > > Doesn't mention why the website went offline a month ago and also doesn't explain why the lists disappeared from GitHub. Did you read my question in full?
> > 
> > 
> > if you knew the website is up and files are available on the website and not here in github, you could have already guessed that their was some issue storing the lists here in github!
> > and, the website went offline because we had an issue with the previous server.
> 
> Seems odd that the website went offline and the GitHub lists also were removed at the same time and no solid explanation as to why. I'm trying to find an answer but I'm having to dig around for it.

nope. let me correct you here. We were using Github as primary storage for the lists, but the blob size here at Github was getting bigger, so we had to store them elsewhere. And it was a long ago, i couldnt even remember the exact time. Then we moved to server solution. So the files from Github weren't removed at the same time! 

Few months ago, our previous server was DDoS'd, and build server with website went down, which took us a bit long to solve and get the service back up!

**Comment by gyCfjSnO** [comment] 2021-09-18 15:01
> > > > > > Can anyone explain what happened and why the blocklists all disappeared from GitHub
> > > > > 
> > > > > 
> > > > > check at website instead [energized.pro ](https://energized.pro)
> > > > 
> > > > 
> > > > Doesn't mention why the website went offline a month ago and also doesn't explain why the lists disappeared from GitHub. Did you read my question in full?
> > > 
> > > 
> > > if you knew the website is up and files are available on the website and not here in github, you could have already guessed that their was some issue storing the lists here in github!
> > > and, the website went offline because we had an issue with the previous server.
> > 
> > 
> > Seems odd that the website went offline and the GitHub lists also were removed at the same time and no solid explanation as to why. I'm trying to find an answer but I'm having to dig around for it.
> 
> nope. let me correct you here. We were using Github as primary storage for the lists, but the blob size here at Github was getting bigger, so we had to store them elsewhere. And it was a long ago, i couldnt even remember the exact time. Then we moved to server solution. So the files from Github weren't removed at the same time!
> 
> Few months ago, our previous server was DDoS'd, and build server with website went down, which took us a bit long to solve and get the service back up!

Thank you for the detailed reply it's greatly appreciated! ❤️
